CREATE TABLE ASSOCIADO (
  idASSOCIADO INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  CPF_CNPJ VARCHAR(14) NULL,
  NOME_RAZAOSOCIAL VARCHAR(90) NULL,
  TIPO_PF_PJ VARCHAR(2) NULL,
  ENDERECO VARCHAR(60) NULL,
  NUMERO INTEGER UNSIGNED NULL,
  BAIRRO VARCHAR(40) NULL,
  CIDADE VARCHAR(40) NULL,
  ESTADO VARCHAR(2) NULL,
  CEP VARCHAR(8) NULL,
  EMAIL VARCHAR NULL,
  FONE VARCHAR(10) NULL,
  FONECEL VARCHAR(10) NULL,
  PRIMARY KEY(idASSOCIADO)
);

CREATE TABLE ESTABELECIMENTO (
  idESTABELECIMENTO INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  RAZAOSOCIAL VARCHAR(60) NULL,
  ENDERECO VARCHAR(60) NULL,
  NUMERO INTEGER UNSIGNED NULL,
  BAIRRO VARCHAR(40) NULL,
  CIDADE VARCHAR(40) NULL,
  ESTADO VARCHAR(2) NULL,
  CEP VARCHAR(8) NULL,
  EMAIL VARCHAR(40) NULL,
  FONE VARCHAR(10) NULL,
  QTDVAGAS INTEGER UNSIGNED NULL,
  ATDVAGASDISPONIVEIS INTEGER UNSIGNED NULL,
  PRIMARY KEY(idESTABELECIMENTO)
);

CREATE TABLE ETIQUETA (
  idETIQUETA INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  MOVIMENTOESTABELECIMENTO_idMOVIMENTOESTABELECIMENTO INTEGER UNSIGNED NOT NULL,
  ASSOCIADO_idASSOCIADO INTEGER UNSIGNED NOT NULL,
  idASSOCIADO INTEGER UNSIGNED NULL,
  SALDO DOUBLE PRECISION NULL,
  DTINICIO DATETIME NULL,
  SITUACAO VARCHAR(20) NULL,
  idMOVIMENTACAOCD_ATIVA INTEGER UNSIGNED NULL,
  PRIMARY KEY(idETIQUETA),
  INDEX ETIQUETA_FKIndex1(ASSOCIADO_idASSOCIADO),
  INDEX ETIQUETA_FKIndex2(MOVIMENTOESTABELECIMENTO_idMOVIMENTOESTABELECIMENTO)
);

CREATE TABLE FORMAPAGAMENTO (
  idFORMAPAGAMENTO INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  DESCRICAO VARCHAR(50)) NULL,
  PRIMARY KEY(idFORMAPAGAMENTO)
);

CREATE TABLE FUNCIONARIO (
  idFUNCIONARIO INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  ESTABELECIMENTO_idESTABELECIMENTO INTEGER UNSIGNED NOT NULL,
  CPF VARCHAR(11) NULL,
  NOME VARCHAR(60) NULL,
  NUMERO INTEGER UNSIGNED NULL,
  BAIRRO VARCHAR(40) NULL,
  CIDADE VARCHAR(40) NULL,
  ESTADO VARCHAR(2) NULL,
  CEP VARCHAR(8) NULL,
  EMAIL VARCHAR(40) NULL,
  idESTABELECIMENTO INTEGER UNSIGNED NULL,
  idTIPOFUNCIONARIO INTEGER UNSIGNED NULL,
  FONE VARCHAR(10) NULL,
  FOTO VARCHAR(60) NULL,
  PRIMARY KEY(idFUNCIONARIO),
  INDEX FUNCIONARIO_FKIndex1(ESTABELECIMENTO_idESTABELECIMENTO)
);

CREATE TABLE MOVIMENTOCD (
  idMOVIMENTOCD INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  FUNCIONARIO_idFUNCIONARIO INTEGER UNSIGNED NOT NULL,
  ESTABELECIMENTO_idESTABELECIMENTO INTEGER UNSIGNED NOT NULL,
  ETIQUETA_idETIQUETA INTEGER UNSIGNED NOT NULL,
  VALOR DOUBLE PRECISION NULL,
  CR VARCHAR(1) NULL,
  idETIQUETA INTEGER UNSIGNED NULL,
  idESTABELECIMENTO INTEGER UNSIGNED NULL,
  DATAHORA DATETIME NULL,
  TIPO VARCHAR(20) NULL,
  idFUNCIONARIO INTEGER UNSIGNED NULL,
  PRIMARY KEY(idMOVIMENTOCD),
  INDEX MOVIMENTOCD_FKIndex1(ETIQUETA_idETIQUETA),
  INDEX MOVIMENTOCD_FKIndex2(ESTABELECIMENTO_idESTABELECIMENTO),
  INDEX MOVIMENTOCD_FKIndex3(FUNCIONARIO_idFUNCIONARIO)
);

CREATE TABLE MOVIMENTOESTABELECIMENTO (
  idMOVIMENTOESTABELECIMENTO INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  ESTABELECIMENTO_idESTABELECIMENTO INTEGER UNSIGNED NOT NULL,
  ASSOCIADO_idASSOCIADO INTEGER UNSIGNED NOT NULL,
  idESTABELECIMENTO INTEGER UNSIGNED NULL,
  idASSOCIADO INTEGER UNSIGNED NULL,
  DATAHORAINI DATETIME NULL,
  DATAHORAFIM DATETIME NULL,
  VALOR DOUBLE PRECISION NULL,
  PRIMARY KEY(idMOVIMENTOESTABELECIMENTO),
  INDEX MOVIMENTOESTABELECIMENTO_FKIndex1(ASSOCIADO_idASSOCIADO),
  INDEX MOVIMENTOESTABELECIMENTO_FKIndex2(ESTABELECIMENTO_idESTABELECIMENTO)
);

CREATE TABLE MOV_EST_FORMAPAGAMENTO (
  idMOV_EST_FORMAPAGAMENTO INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  FORMAPAGAMENTO_idFORMAPAGAMENTO INTEGER UNSIGNED NOT NULL,
  ETIQUETA_idETIQUETA INTEGER UNSIGNED NOT NULL,
  MOVIMENTOESTABELECIMENTO_idMOVIMENTOESTABELECIMENTO INTEGER UNSIGNED NOT NULL,
  idMOVIMENTOESTABELECIMENTO INTEGER UNSIGNED NULL,
  VALOR DOUBLE PRECISION NULL,
  idFORMAPAGAMENTO INTEGER UNSIGNED NULL,
  idETIQUETA INTEGER UNSIGNED NULL,
  PRIMARY KEY(idMOV_EST_FORMAPAGAMENTO),
  INDEX MOV_EST_FORMAPAGAMENTO_FKIndex1(MOVIMENTOESTABELECIMENTO_idMOVIMENTOESTABELECIMENTO),
  INDEX MOV_EST_FORMAPAGAMENTO_FKIndex2(ETIQUETA_idETIQUETA),
  INDEX MOV_EST_FORMAPAGAMENTO_FKIndex3(FORMAPAGAMENTO_idFORMAPAGAMENTO)
);

CREATE TABLE TIPOFUNCIONARIO (
  idTIPOFUNCIONARIO INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  FUNCIONARIO_idFUNCIONARIO INTEGER UNSIGNED NOT NULL,
  DESCRICAO VARCHAR(30) NULL,
  GERENTE VARCHAR(1) NULL,
  PRIMARY KEY(idTIPOFUNCIONARIO),
  INDEX TIPOFUNCIONARIO_FKIndex1(FUNCIONARIO_idFUNCIONARIO)
);


